import { Category } from "@/components/categories-grid"
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"
import {
  Smartphone,
  Laptop,
  Sparkles,
  Home,
  Shirt,
  Watch,
  Car,
  ShoppingBag,
  Glasses,
  Lightbulb,
  Bike,
  Gem,
  UtensilsCrossed,
  Sofa,
  Crown,
  TrendingUp,
  Star,
   ArrowRight,
  Filter,
  Grid3X3,
} from "lucide-react"



export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}


export const categories: Category[] = [
  {
    id: "smartphones",
    name: "smartphones",
    label: "Smartphones",
    description: "Latest mobile phones and accessories",
    icon: Smartphone,
    count: 194,
    color: "text-blue-600",
    gradient: "from-blue-500 to-cyan-500",
    featured: true,
    trending: true,
  },
  {
    id: "laptops",
    name: "laptops",
    label: "Laptops",
    description: "High-performance computers and notebooks",
    icon: Laptop,
    count: 114,
    color: "text-purple-600",
    gradient: "from-purple-500 to-pink-500",
    featured: true,
  },
  {
    id: "fragrances",
    name: "fragrances",
    label: "Fragrances",
    description: "Premium perfumes and colognes",
    icon: Sparkles,
    count: 25,
    color: "text-pink-600",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "skincare",
    name: "skincare",
    label: "Skincare",
    description: "Beauty and skincare essentials",
    icon: Sparkles,
    count: 30,
    color: "text-rose-600",
    gradient: "from-rose-500 to-pink-500",
    trending: true,
  },
  {
    id: "groceries",
    name: "groceries",
    label: "Groceries",
    description: "Fresh food and daily essentials",
    icon: UtensilsCrossed,
    count: 25,
    color: "text-green-600",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "home-decoration",
    name: "home-decoration",
    label: "Home Decoration",
    description: "Beautiful decor for your living space",
    icon: Home,
    count: 30,
    color: "text-orange-600",
    gradient: "from-orange-500 to-red-500",
    featured: true,
  },
  {
    id: "furniture",
    name: "furniture",
    label: "Furniture",
    description: "Stylish furniture for every room",
    icon: Sofa,
    count: 25,
    color: "text-amber-600",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "tops",
    name: "tops",
    label: "Tops & T-Shirts",
    description: "Trendy tops and casual wear",
    icon: Shirt,
    count: 40,
    color: "text-indigo-600",
    gradient: "from-indigo-500 to-blue-500",
  },
  {
    id: "womens-dresses",
    name: "womens-dresses",
    label: "Women's Dresses",
    description: "Elegant dresses for every occasion",
    icon: Crown,
    count: 20,
    color: "text-purple-600",
    gradient: "from-purple-500 to-violet-500",
    trending: true,
  },
  {
    id: "womens-shoes",
    name: "womens-shoes",
    label: "Women's Shoes",
    description: "Stylish footwear collection",
    icon: ShoppingBag,
    count: 40,
    color: "text-pink-600",
    gradient: "from-pink-500 to-purple-500",
  },
  {
    id: "mens-shirts",
    name: "mens-shirts",
    label: "Men's Shirts",
    description: "Professional and casual shirts",
    icon: Shirt,
    count: 20,
    color: "text-slate-600",
    gradient: "from-slate-500 to-gray-500",
  },
  {
    id: "mens-shoes",
    name: "mens-shoes",
    label: "Men's Shoes",
    description: "Quality footwear for men",
    icon: ShoppingBag,
    count: 40,
    color: "text-gray-600",
    gradient: "from-gray-500 to-slate-500",
  },
  {
    id: "mens-watches",
    name: "mens-watches",
    label: "Men's Watches",
    description: "Luxury and sport timepieces",
    icon: Watch,
    count: 20,
    color: "text-blue-600",
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    id: "womens-watches",
    name: "womens-watches",
    label: "Women's Watches",
    description: "Elegant timepieces for women",
    icon: Watch,
    count: 20,
    color: "text-rose-600",
    gradient: "from-rose-500 to-pink-500",
  },
  {
    id: "womens-bags",
    name: "womens-bags",
    label: "Women's Bags",
    description: "Handbags, purses, and accessories",
    icon: ShoppingBag,
    count: 30,
    color: "text-violet-600",
    gradient: "from-violet-500 to-purple-500",
    featured: true,
  },
  {
    id: "womens-jewellery",
    name: "womens-jewellery",
    label: "Women's Jewelry",
    description: "Beautiful jewelry and accessories",
    icon: Gem,
    count: 30,
    color: "text-yellow-600",
    gradient: "from-yellow-500 to-amber-500",
  },
  {
    id: "sunglasses",
    name: "sunglasses",
    label: "Sunglasses",
    description: "Stylish eyewear and protection",
    icon: Glasses,
    count: 20,
    color: "text-teal-600",
    gradient: "from-teal-500 to-cyan-500",
  },
  {
    id: "automotive",
    name: "automotive",
    label: "Automotive",
    description: "Car accessories and parts",
    icon: Car,
    count: 25,
    color: "text-red-600",
    gradient: "from-red-500 to-orange-500",
  },
  {
    id: "motorcycle",
    name: "motorcycle",
    label: "Motorcycle",
    description: "Bike accessories and gear",
    icon: Bike,
    count: 25,
    color: "text-orange-600",
    gradient: "from-orange-500 to-yellow-500",
  },
  {
    id: "lighting",
    name: "lighting",
    label: "Lighting",
    description: "Modern lighting solutions",
    icon: Lightbulb,
    count: 20,
    color: "text-yellow-600",
    gradient: "from-yellow-500 to-orange-500",
  },
];

export const categories1 = [
  {
    name: "smartphones",
    label: "Smartphones",
    icon: Smartphone,
    count: 194,
    color: "text-blue-600",
    gradient: "from-blue-500 to-cyan-500",
    popular: true,
  },
  {
    name: "laptops",
    label: "Laptops",
    icon: Laptop,
    count: 114,
    color: "text-purple-600",
    gradient: "from-purple-500 to-pink-500",
    popular: true,
  },
  {
    name: "home-decoration",
    label: "Home Decor",
    icon: Home,
    count: 30,
    color: "text-orange-600",
    gradient: "from-orange-500 to-red-500",
    trending: true,
  },
  {
    name: "womens-bags",
    label: "Women's Bags",
    icon: ShoppingBag,
    count: 30,
    color: "text-violet-600",
    gradient: "from-violet-500 to-purple-500",
  },
  {
    name: "mens-watches",
    label: "Men's Watches",
    icon: Watch,
    count: 20,
    color: "text-blue-600",
    gradient: "from-blue-500 to-indigo-500",
  },
  {
    name: "skincare",
    label: "Skincare",
    icon: Sparkles,
    count: 30,
    color: "text-rose-600",
    gradient: "from-rose-500 to-pink-500",
    trending: true,
  },
  {
    name: "furniture",
    label: "Furniture",
    icon: Sofa,
    count: 25,
    color: "text-amber-600",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    name: "automotive",
    label: "Automotive",
    icon: Car,
    count: 25,
    color: "text-red-600",
    gradient: "from-red-500 to-orange-500",
  },
];




export const categoryGroups = [
  {
    title: "Electronics & Tech",
    description: "Latest gadgets and technology",
    color: "from-blue-500 to-cyan-500",
    categories: [
      { name: "smartphones", label: "Smartphones", icon: Smartphone, count: 194 },
      { name: "laptops", label: "Laptops", icon: Laptop, count: 114 },
    ],
  },
  {
    title: "Fashion & Style",
    description: "Trendy clothing and accessories",
    color: "from-purple-500 to-pink-500",
    categories: [
      { name: "womens-dresses", label: "Women's Dresses", icon: Crown, count: 20 },
      { name: "mens-shirts", label: "Men's Shirts", icon: Shirt, count: 20 },
      { name: "womens-bags", label: "Women's Bags", icon: ShoppingBag, count: 30 },
      { name: "sunglasses", label: "Sunglasses", icon: Glasses, count: 20 },
    ],
  },
  {
    title: "Home & Living",
    description: "Beautiful items for your home",
    color: "from-orange-500 to-red-500",
    categories: [
      { name: "furniture", label: "Furniture", icon: Sofa, count: 25 },
      { name: "home-decoration", label: "Home Decor", icon: Home, count: 30 },
      { name: "lighting", label: "Lighting", icon: Lightbulb, count: 20 },
    ],
  },
  {
    title: "Beauty & Wellness",
    description: "Self-care and beauty essentials",
    color: "from-rose-500 to-pink-500",
    categories: [
      { name: "skincare", label: "Skincare", icon: Sparkles, count: 30 },
      { name: "fragrances", label: "Fragrances", icon: Sparkles, count: 25 },
    ],
  },
];



export const categories2 = [
  { value: "smartphones", label: "Smartphones", count: 194 },
  { value: "laptops", label: "Laptops", count: 114 },
  { value: "fragrances", label: "Fragrances", count: 25 },
  { value: "skincare", label: "Skincare", count: 30 },
  { value: "groceries", label: "Groceries", count: 25 },
  { value: "home-decoration", label: "Home Decoration", count: 30 },
  { value: "furniture", label: "Furniture", count: 25 },
  { value: "tops", label: "Tops", count: 40 },
  { value: "womens-dresses", label: "Women's Dresses", count: 20 },
  { value: "womens-shoes", label: "Women's Shoes", count: 40 },
  { value: "mens-shirts", label: "Men's Shirts", count: 20 },
  { value: "mens-shoes", label: "Men's Shoes", count: 40 },
  { value: "mens-watches", label: "Men's Watches", count: 20 },
  { value: "womens-watches", label: "Women's Watches", count: 20 },
  { value: "womens-bags", label: "Women's Bags", count: 30 },
  { value: "womens-jewellery", label: "Women's Jewellery", count: 30 },
  { value: "sunglasses", label: "Sunglasses", count: 20 },
  { value: "automotive", label: "Automotive", count: 25 },
  { value: "motorcycle", label: "Motorcycle", count: 25 },
  { value: "lighting", label: "Lighting", count: 20 },
]

export const sortOptions = [
  { value: "default", label: "Default" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "name-asc", label: "Name: A to Z" },
  { value: "name-desc", label: "Name: Z to A" },
  { value: "rating-desc", label: "Highest Rated" },
  { value: "newest", label: "Newest First" },
]

export const ratingOptions = [
  { value: "4", label: "4+ Stars", count: 150 },
  { value: "3", label: "3+ Stars", count: 280 },
  { value: "2", label: "2+ Stars", count: 350 },
  { value: "1", label: "1+ Stars", count: 400 },
]